
- name: Ensure jenkins directory on docker host
  file:
    state: directory
    owner: 1000
    group: 1000
    path: /share/jenkins

- name: Pull the latest official jenkins docker image
  docker_image:
    name: "jenkins:latest"

- name: Create a container from the jenkins docker image
  docker_container:
    name: "jenkins-server"
    image: "jenkins"
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
        - "/share/jenkins:/var/jenkins_home"
    state: present
    recreate: no

- name: Copy systemd service script to start and stop the jenkins container
  copy: src=files/docker-jenkins.service dest=/etc/systemd/system

- name: Reload systemctl
  shell: systemctl reload-or-restart docker-jenkins

- name: Enable the docker-jenkins service
  shell: systemctl enable docker-jenkins

# In a future release of ansible there will be a 'systemd' module which should replace
# the previous systemctl calls.
#- name: Enable the docker-jenkins service (ansible>2.2)
#  systemd:
#    name: "docker-jenkins"
#    daemon_reload: yes
#    enabled: yes
#    state: started

