
- name: Pull the latest official jenkins docker image
  docker_image:
    name: "jenkins:latest"

- name: Create a container from the jenkins docker image
  docker_container:
    name: "jenkins-server"
    image: "jenkins"
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
        - "/share/jenkins:/var/jenkins_home"
    state: present
    recreate: no

- name: Create a systemd service script to start and stop the jenkins container
  copy:
    src: files/docker-jenkins.service
    dest: /etc/systemd/system

- name: Enable the docker-jenkins service
  systemd:
    name: "docker-jenkins"
    daemon-reload: yes
    enabled: yes
    state: started
